# -*- coding: utf-8 -*-
"""python and network secrity

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IUWM8ffxcDcKgw9qzKgviIBJ-US8qFAX
"""

import hashlib
hash_object = hashlib.sha256(b'Hello World')
hex_dig = hash_object.hexdigest()
print(hex_dig)

text = "pushpa latha python mini project"

hash_object = hashlib.md5(text.encode())
md5_hash = hash_object.hexdigest()


print(md5_hash)

